"""added additional columns

Revision ID: 7e3cdd04a289
Revises: c35ea8965d46
Create Date: 2023-07-27 14:40:07.568122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e3cdd04a289'
down_revision = 'c35ea8965d46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('password', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('username', sa.Text(), nullable=True))
        batch_op.drop_column('user')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user', sa.TEXT(), nullable=True))
        batch_op.drop_column('username')
        batch_op.drop_column('password')
        batch_op.drop_column('last')

    # ### end Alembic commands ###
